
web:
  image: rungsikorn/vivid:${VERSION_TAG}
  ports:
    - "3183:3000"
  links:
    - mongo
  environment: 
    MONGO_URI: 'mongo'
    RAVEN_URL: '${RAVEN_URL}'
    COOKIE_SECRET: '${COOKIE_SECRET}'
    ROOT_EMAIL: '${ROOT_EMAIL}'
    ROOT_PASS: '${ROOT_PASS}'
    CLOUDINARY_URL: '${CLOUDINARY_URL}'
    GRAPHQL: '${GRAPHQL_ENDPOINT}'
    NODE_ENV: 'production'
