
cems-museum:
    image: museum
    ports:
        - "3000:3000"
    environment: 
        MONGO_URI: "mongo"
    links:
        - mongo
    volumes:
        - .:/app/build

mongo:
  image: mongo:3.0.8
  ports:
    - "27017:27017"
  volumes: 
    - ./db/:/data/db
