nginx:
  image: nginx
  volumes: 
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  ports:
    - "80:80"
  links:
    - cems-museum:web

mongo:
  image: mongo:3.0.8 
  ports:
    - "27017:27017"

cems-museum:
    image: museum
    ports:
        - "3000:3000"
    environment: 
        MONGO_URI: "mongo"
    links:
        - mongo

