nginx:
  image: nginx
  volumes: 
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  ports:
    - "80:80"
  links:
    - cems-museum:web

mongo:
  image: mongo:3.0.8 
  volumes_from:
    - mongo-data
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null --setParameter failIndexKeyTooLong=false"

mongo-data:
  image: mongo
  volumes:
    - ./db/:/data/db
  command: "--break-mongo" # break mongod command and use it as data-volume-container

cems-museum:
    image: museum
    ports:
        - "3000:3000"
    environment: 
        MONGO_URI: "mongo"
    links:
        - mongo